server {
    listen 80;
    server_name d00pa.pl;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name d00pa.pl;

    ssl_certificate /etc/letsencrypt/live/d00pa.pl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/d00pa.pl/privkey.pem;

    location / {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
